sudo: required

dist: xenial
language: go

branches:
  only:
  - master
  - master-v2.0
  - future

go:
  - "1.10.x"

env:
  global:
    - GO_USR_DIRS=$(go list -f {{.Dir}} ./... | grep -E -v "/gen-go/|/vendor/")

services:
  - docker

before_install:
  - go get golang.org/x/tools/cmd/goimports
  - test -z "`for d in $GO_USR_DIRS; do goimports -d $d/*.go | tee /dev/stderr; done`"

install:
  - docker-compose up -d

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v github.com/paypal/gorealis

after_success:
  - bash <(curl -s https://codecov.io/bash)
