// Autogenerated by Thrift Compiler (1.0.0-dev)
// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package aurora

var GoUnusedProtection__ int
